



from service.oop.hms.exception import *




# try / except / else / finally 실습해보기

userInput()
print('after userInput()')





# Exception() : 인위적으로 에러를 발생 시키기!


list01 = [1, 2, 3, 4]
exceptionFunc(list01)

list02 = [1, 2]
exceptionFunc(list02)

list03 = [1, 2, 3, -100]
exceptionFunc(list03)













# Exception() 함수 실습해보기

temp_list = [10, 20, 25, '문짜!', 40, 50]
listExcepFunc(temp_list)

listExepFunc02(temp_list)












































